name: CI - Playwright UI + API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: my-app-backend/node_modules
          key: ${{ runner.os }}-node-my-app-backend-${{ hashFiles('my-app-backend/package-lock.json') }}

      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: my-app-frontend/node_modules
          key: ${{ runner.os }}-node-my-app-frontend-${{ hashFiles('my-app-frontend/package-lock.json') }}

      - name: Cache test framework dependencies
        uses: actions/cache@v3
        with:
          path: MyAppPlaywrightFramework/node_modules
          key: ${{ runner.os }}-node-MyAppPlaywrightFramework-${{ hashFiles('MyAppPlaywrightFramework/package-lock.json') }}

      - name: Install backend dependencies
        run: npm install
        working-directory: ./my-app-backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./my-app-frontend

      - name: Install test framework dependencies
        run: npm install
        working-directory: ./MyAppPlaywrightFramework

      - name: Start backend server (port 4000)
        run: nohup node server.js > backend.log 2>&1 &
        working-directory: ./my-app-backend

      - name: Start frontend server (port 3000)
        run: BROWSER=none nohup npm run start > frontend.log 2>&1 &
        working-directory: ./my-app-frontend

      - name: Check running node processes and open ports (for debugging)
        run: |
          echo "Node processes:"
          ps aux | grep node || echo "No node processes"
          echo "Open TCP ports:"
          netstat -tuln || echo "netstat not available"
          ss -tuln || echo "ss not available"

      - name: Wait for backend (port 4000)
        run: npx wait-on tcp:4000 --timeout 60000
        working-directory: ./MyAppPlaywrightFramework

      - name: Wait for frontend (port 3000)
        run: npx wait-on tcp:3000 --timeout 120000
        working-directory: ./MyAppPlaywrightFramework

      - name: Test access to frontend
        run: curl -I http://localhost:3000 || echo "Frontend not reachable"

      - name: Test access to backend
        run: curl -I http://localhost:4000 || echo "Backend not reachable"

      - name: Print backend log if wait failed
        if: failure()
        run: cat ./my-app-backend/backend.log || echo "No backend log"

      - name: Print frontend log if wait failed
        if: failure()
        run: cat ./my-app-frontend/frontend.log || echo "No frontend log"

      - name: Fix Playwright CLI permissions
        run: chmod +x ./node_modules/.bin/playwright
        working-directory: ./MyAppPlaywrightFramework

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./MyAppPlaywrightFramework

      - name: Run Playwright tests (UI)
        run: npx playwright test
        working-directory: ./MyAppPlaywrightFramework

      - name: Run API tests + Coverage
        run: npx nyc npm test
        working-directory: ./my-app-backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: my-app-backend/coverage

      - name: Clean up backend and frontend servers
        run: |
          echo "Stopping all node processes..."
          pkill -f "node" || true
